# -*- coding: utf-8 -*-
"""Numpy-self_trained_glove_vector_model_to_find_the_embedding_of_the_given_word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzP-yof9rvbWEq2Kqmf7YaQX02vhLpX4
"""

import numpy as np

def load_glove_embeddings(file_path):

    embeddings = {}

    with open(file_path, 'r', encoding='utf8') as f:

        for line in f:

            values = line.split()

            word = values[0]

            vector = np.asarray(values[1:], dtype='float32')

            embeddings[word] = vector

    return embeddings



# Download and unzip e.g. glove.6B.50d.txt from the GloVe website

glove_path = '/content/sample_data/glove.6B.50d.txt'

embeddings = load_glove_embeddings(glove_path)



word = 'cat'

if word in embeddings:

    print(f"Embedding for '{word}':\n{embeddings[word]}")

else:

    print(f"Word '{word}' not found in GloVe vocabulary.")