# -*- coding: utf-8 -*-
"""list_of_models_in_ChatGPT_Gemini_and_hugging_face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TT3q2Z-5sk1hB3bCHO9NMCUOOrHuDAzy
"""

!pip install huggingface_hub
!pip install google-generativeai
from huggingface_hub import HfApi
import google.generativeai as genai #Gemini libraries
import openai #ChatGpt libraires
from openai import OpenAI

#step 1: hugging face models
def get_huggingface_models():
    # Initialize the Hugging Face API
    api = HfApi()

    # Fetch the list of models
    models = api.list_models()
    #print(f"Total models: {len(list(models))}") # Corrected indentation

    num=1

    #print only first 10 models
    # Print details of the models
    for model in models:
        print(f"Model ID: {model.modelId}")
        print(f"Model Name: {model.modelId}")
        print(f"Pipeline Tag: {model.pipeline_tag}")
        print(f"Tags: {model.tags}")
        print("-" * 80)
        num+=1
        print('\n')
        if num==1:#print desired number of models
            break;

#step 2: gimini models
def get_gimini_models():
    #gimni key
    API_KEY = "AIzaSyB0Brktm7-Xp-Hn133AQ6Ot_uIeKEl6vCg"
    genai.configure(api_key=API_KEY)
    for m in genai.list_models():
     if 'generateContent' in m.supported_generation_methods:
      print(m.name)

#step 3: Chat GPT models
def get_chat_gpt_models():
  apiKey=''

  client=OpenAI(api_key=apiKey)
  models=client.models.list()

  for model in models.data:
    print(model)

if __name__ == "__main__":
    #get huggingface models
    print("---------------------Hugging Face Models Start---------------------")
    get_huggingface_models();
    print("---------------------Hugging Face Models END---------------------")

    #get Gemini models
    print("---------------------Gemini Models Start---------------------")
    get_gimini_models();
    print("---------------------Gemini  Models END---------------------")

    #get Chat GPT models
    print("---------------------Chat GPT Models Start---------------------")
    get_chat_gpt_models();
    print("---------------------Chat GPT  Models END---------------------")

